server:
  port: 9000
 
#jsp setting
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  
#mysql setting    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-324obn-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    username: study
    password: bitcamp!@#123 

#mybatis settings
mybatis:
  type-aliases-package: data.dto
  mapper-locations:
  - /mapper/**/*.xml

#league of legend api key
riot:
  api:
    key: "RGAPI-f39f6383-7fef-49c4-b959-89c315d0e2df"
